---
- hosts: localhost
  gather_facts: false
   
  vars:
    my_list:
    - "1) A hyphen represents an item on a list"
    - "2) So the second item on the list is this"
    - "3) Whereas this would be the third"
    - "4) Item var is always replaced by an item from the loop list"

  tasks:
      - name: "learning about debug mod"
        debug:
            msg: "debug allows... --> {{item}}"
        loop: "{{my_list}}"
